"""decisions et structuration CR

Revision ID: 1971bfb3886c
Revises: 5edc2dbc742d
Create Date: 2026-07-10 18:35:15.739347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '1971bfb3886c'
down_revision: Union[str, None] = '5edc2dbc742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ministere', sa.String(length=300), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_statut_validation'), 'decision', ['statut_validation'], unique=False)
    op.create_index(op.f('ix_decision_type'), 'decision', ['type'], unique=False)
    op.add_column('document', sa.Column('date_structuration', sa.DateTime(timezone=True), nullable=True))
    # NB : la colonne générée document.tsv (recherche plein texte) est gérée en SQL
    # brut dans la migration initiale et volontairement absente de l'ORM - ne pas
    # laisser l'autogénération la supprimer (filtre include_name dans env.py).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'date_structuration')
    op.drop_index(op.f('ix_decision_type'), table_name='decision')
    op.drop_index(op.f('ix_decision_statut_validation'), table_name='decision')
    op.drop_table('decision')
    # ### end Alembic commands ###
