"""finances : engagements et budgets

Revision ID: 740a30fefef4
Revises: 1971bfb3886c
Create Date: 2026-07-11 02:34:02.438938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '740a30fefef4'
down_revision: Union[str, None] = '1971bfb3886c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_exercice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('type_loi', sa.String(length=20), nullable=False),
    sa.Column('recettes_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('depenses_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_exercice_exercice'), 'budget_exercice', ['exercice'], unique=False)
    op.create_index(op.f('ix_budget_exercice_statut_validation'), 'budget_exercice', ['statut_validation'], unique=False)
    op.create_table('engagement_financier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ministere', sa.String(length=300), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('beneficiaire', sa.String(length=500), nullable=True),
    sa.Column('montant_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_financier_montant_fcfa'), 'engagement_financier', ['montant_fcfa'], unique=False)
    op.create_index(op.f('ix_engagement_financier_statut_validation'), 'engagement_financier', ['statut_validation'], unique=False)
    op.create_index(op.f('ix_engagement_financier_type'), 'engagement_financier', ['type'], unique=False)
    # (l'index ix_document_tsv est géré en SQL brut - exclu de l'autogénération via env.py)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engagement_financier_type'), table_name='engagement_financier')
    op.drop_index(op.f('ix_engagement_financier_statut_validation'), table_name='engagement_financier')
    op.drop_index(op.f('ix_engagement_financier_montant_fcfa'), table_name='engagement_financier')
    op.drop_table('engagement_financier')
    op.drop_index(op.f('ix_budget_exercice_statut_validation'), table_name='budget_exercice')
    op.drop_index(op.f('ix_budget_exercice_exercice'), table_name='budget_exercice')
    op.drop_table('budget_exercice')
    # ### end Alembic commands ###
